export const FETCH_CURRENT_WEATHER =  'FETCH_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCESS =  'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAIL =  'FETCH_CURRENT_WEATHER_FAIL';
export const RETRIEVE_LOCATION = "RETRIEVE_LOCATION";
export const RETRIEVE_LOCATION_FAIL = "RETRIEVE_LOCATION_FAIL";