export const FETCH_CURRENT_WEATHER =  'FETCH_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_SUCCESS =  'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_FAIL =  'FETCH_CURRENT_WEATHER_FAIL';